### ISSUE TITLE
Nhập dữ liệu sai

### ISSUE THREAD

**Issue by khue856593** [Phu1237/software_testing_group9#1]
![image](https://user-images.githubusercontent.com/62629086/84345917-e31f8200-abd8-11ea-8921-9e7fa443b926.png)
- Nhập chữ cái thì bị lỗi

**Comment by Phu1237** [comment]
![image](https://user-images.githubusercontent.com/9032235/84347549-119f5c00-abdd-11ea-8709-fee9af77168e.png)
![image](https://user-images.githubusercontent.com/9032235/84347591-2bd93a00-abdd-11ea-92e9-29df5bdece2b.png)
- Đã sửa
