### ISSUE TITLE
Lỗi nhập số giá trị lớn

### ISSUE THREAD

**Issue by khue856593** [Phu1237/software_testing_group9#10]
![image](https://user-images.githubusercontent.com/62629086/84346959-722d9980-abdb-11ea-9845-0b3abe0c7da5.png)
- Không nhập được số b

**Comment by Phu1237** [comment]
![image](https://user-images.githubusercontent.com/9032235/84348692-c76baa00-abdf-11ea-9652-6e926df16847.png)
- Đã sửa
