### ISSUE TITLE
Lỗi tính toán

### ISSUE THREAD

**Issue by khue856593** [Phu1237/software_testing_group9#7]
![image](https://user-images.githubusercontent.com/62629086/84346678-b9fff100-abda-11ea-88dc-e8ed98af2886.png)
- Tính sai hiệu

**Comment by Phu1237** [comment]
![image](https://user-images.githubusercontent.com/9032235/84348441-1fee7780-abdf-11ea-8fa9-ffbe4927b0f2.png)
- Đã sửa
