### ISSUE TITLE
Lỗi nhập số thực

### ISSUE THREAD

**Issue by khue856593** [Phu1237/software_testing_group9#9]
![image](https://user-images.githubusercontent.com/62629086/84346835-1a8f2e00-abdb-11ea-9ec2-7012b346ff40.png)
- Không nhập được số b

**Comment by Phu1237** [comment]
![image](https://user-images.githubusercontent.com/9032235/84348559-7360c580-abdf-11ea-8127-72f285065245.png)
- Đã sửa
